export const FILM_REQUEST_FETCHING = 'FILM_REQUEST_FETCHING';
export const FILM_REQUEST_SUCCESS = 'FILM_REQUEST_SUCCESS';
export const FILM_REQUEST_FAILURE = 'FILM_REQUEST_FAILURE';
export const FILM_SET_ID = 'FILM_SET_ID';
export const FILM_CLEAR = 'FILM_CLEAR';
